### ISSUE TITLE
Request to pull latest trunk from selenium

### ISSUE THREAD

**Issue by brianburdan** [hacklschorsch/selenium-webdriverjs#1]
Hey,

We are using your repo for our selenium base, and there is an issue that was recently fixed in selenium trunk.  Was hoping we could get you to update your repo code with the latest from selenium trunk.  Otherwise we will need to fork the repo to do so.

Here is a link to the issue that was fixed recently:
http://code.google.com/p/selenium/issues/detail?id=4649

Thanks!

**Comment by hacklschorsch** [comment]
Done!

I had written update.sh to be able to update automatically, but since trunk webdriver.js was broken more often than not for me I haven't put in automatic publishing. Upstream has now changed the file layout. Since this is a quite a change for the package (but not for its external interface) I have bumped the minor version number of the package. 

Glad the package is useful to you!
